spring:
  application:
    name: video-spider
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/file
  redis:
    host: 127.0.0.1
    port: 6379
    connect-timeout: 5s
    jedis:
      pool:
        max-active: 50
  elasticsearch:
    rest:
      uris: http://localhost:9200
      connection-timeout: 3s
  servlet:
    multipart:
      maxFileSize: 10GB
      maxRequestSize: 10GB
  profiles:
    active:
    include: web

limit:
  bucket: 100
  rate: 10
  time: 100

proxy:
  enabled: false
  socks:
    host: 127.0.0.1
    port: 10808
  http:
    host: 127.0.0.1
    port: 10809

FFmpegPath: C:\\ffmpeg\\bin\\


server:
  port: 80
  undertow:
    threads:
      worker: 50
      io: 6
    url-charset: UTF-8
    direct-buffers: true
    accesslog:
      enabled: true

management:
  auditevents:
    enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

#zookeeper:
#  host: 127.0.0.1
#  port: 2181

#logging:
#  level:
#    root: info
#    org.mybatis: debug
#    java.sql: debug
#    org.springframework.web: trace
  

